server:
  #端口号
  port: 8081
  servlet:
    #应用的访问路径
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rent?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  security:
    user:
      name: root
      password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


mybatis:
  #配置别名
  type-aliases-package: com.koko.pojo
  #配置mapper文件地址
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰映射
    map-underscore-to-camel-case: true

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: 5d7ae5b5cd624dc89b80e2392a605304
  # 令牌有效期（默认30分钟）
  expireTime: 30

file:
  base-upload-path: C:/Users/13629/Desktop/
  base-download-path: C:/Users/13629/Desktop/

#日志配置
logging:
  level:
    com.koko: debug

#PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql