server:
  #端口号
  port: 8080
  servlet:
    #应用的访问路径
    context-path: /

spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/car_rent?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  #安全配置
  security:
    user:
      name: root
      password: root
  #文件上传配置
  servlet:
    multipart:
      #单个文件大小
      max-file-size: 10MB
      #总上传大小
      max-request-size: 10MB
  #Redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000


mybatis:
  #配置别名
  type-aliases-package: com.koko.pojo
  #配置mapper文件地址
  mapper-locations: classpath:mappers/*.xml
  configuration:
    #开启驼峰映射
    map-underscore-to-camel-case: true

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: 5d7ae5b5cd624dc89b80e2392a605304
  # 令牌有效期（默认30分钟）
  expireTime: 30

file:
  base-upload-path: C:/Users/13629/Desktop/
  base-download-path: C:/Users/13629/Desktop/

ucloud:
  ufile:
    public-key: RAUhpMwnOluyRxJIRtn37NtLbg30z49NZ5UICoHr
    private-key: L2k6iWLd1DPNr3R4Tx_k0L7Y1fq9r2geoK9yda0eczaJx2JG64VIa0NR2NQIGecP
    bucketName: dreamland
    region: cn-bj
    proxySuffix: ufileos.com
    expires: 31536000
    folder: car-rental/


#日志配置
logging:
  level:
    com.koko: debug

#PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

alipay:
  app-id: 2021000117628129
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCBrqiNoFTNnZ1WJJPtbyFuJT0HuYKUFM44LKK/CEuiGFpmxhIBPLIjN5XXHAZajD1xukKpqPHdLdDcEWGNEQOVNfsiNHvVe4G+BCn+UmCizIXb+Pgji/mPvX9UC3ij3McRHxYvvBjQSPL/Ae/HyK03sFjjIke05ec8Y/Q+cfl+FkvTwy7LBBX3u2V8xOYKbDkW3NvFM/Cd/PXwasZGbyQVBH6xiRogtp0z2UR2MIPZdB7iKw/maX/cDC974eMRaABwveOJCBdj4OhPgL9YcLGAH/aZd5JL1v842QFpZ8/U6NeMBTeIvZDFH74+/P5dufCbaV1R4Qwc+62Rf8S0UcrnAgMBAAECggEAA7jYm6ADbxdcAbHxEPqEkh29f7BCYC+sr44Qab06Nn/OcG6065YrYrlgspjaUdT+mnoHGcmAj6GWAgr5qsvXN3wiJhwthbYSxjpmXidNIL8QBH1D2flVg1ukAOyHXOSkTgh/YYVbjPbbCpiqoihPWG7WTkaYmkeS+HfB9dzdlVHRny1WbhxCB4ZVcnBYAQ5tXdby/xQ7y8zf84zk+Q03nwVKsZQxPIbJzsqqjKWE4hvUmpW6VF0gxgqsUUyCwArT481AltFI5123joKS7Jjg0UScbz096Oh55yFmr253NXZ/XFWriY408+OwfF7IYNVkkk/SJtOUP4MIstG4zT39aQKBgQDyAxrAsp4kTBeIgwFfBQQ8a5ov+jBQsikKY8S5PdQ0CDI374OGyJ+HEQZvfUU7NZ4n1VXZhxULdh/j733b5sVjUBVMdqMjSigTQc7SPCjBHoGFVtZ0K6f7rnm0AHZ6lvZ//t3IdLKjXg9a1HX4HwWFc4Dx9zAt/HP14hHT0HHRGwKBgQCJLXtvZTMpF4Qn/xmd95oDcAPQ8aJ3xIpTMrV+rsE5yGBD6t3cMdfkPsuSg5frdrC2noxpZYczUf3wXd5fjgtIQMIfkYbhOvtCLEycPr2bb7b7AvrJLiYxdYIIS4ZotrST3ZVrGcsqFtCkvCZLBsy5lqNazF6EsswCjx33kFbWJQKBgDzZZvqYboa10xzxw4B+pGgErgnuIAPKJ+OC3k2tLBPBE89Ym3tiKiotr66MksGmY5OkYieFfVcaZj5LUxvdVDf6RMCq+6290YG2BCh8E8sqvmomQVmIOH5hihwmGaQNHQFltaHXJatJ1RaDYP333s2FEyDDhAur9AQYyV62hEeNAoGAJUU0OknWop1/DJbk0OSK9dAjWUuthrjhlEU8xpSYbyif7xQK/16Td7IQAVi7mAABdzyQjbpGB42JXxtB5dhj/FeL5qPVb7Bkv8/laLYrMeYiYwSmOq7NNbblg3dxp1WsrlgP1q+FYYQdYAS2qr/IM8xXyb2pGIizoSZdT/vpe/kCgYEAj9cshJyKjYzv5UhGaIMUGA/+5BP9g5czduYyUYHJhNUyFkv9AVAkWOwVXnm3uDBsqrefwLt1ZWEUVoKVE31ZCcutyOLHoXhKdOaLEtciC9JJglZ6frHI8j5RFuKePzRXM4tXpWcXQJsoW4dXC0N/B4a5zK2nai2H5XttfMRHL1Q=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuciHXno5tdFz8DWPn0LquUChl8EmW7qC7T7jStthmrlVGtll0zQYXhhS2TfD1Vf1oV03zYvz54aQnQhNtvvFJSi9NWevXkl7ZiFiuo0lptACqHfdfLNFoO7QglriwA2OZjh2OMcscPRAPIEemg0U3YINtKzMkP9LOoiGIVM73A+bXE0ON5rt417ntwDvKwHT5QOfD5e1w3hSQ3n0wqUS2IZDSpmcaAYc1Y3IS53F4uJlgZNUVOF7nId7qb2NwsDbYIxPHBiU+v2bxFy0GN84tsNyML/bs11xRyCSpY777RE1IZ83yQTTniU84Gss6FV1q9QkyzyayYLwxOwbmLlFIwIDAQAB
  sign-type: RSA2
  charset: utf-8
  gateway-url: https://openapi.alipaydev.com/gateway.do
  notify-url: http://127.0.0.1:8080/notify
  return-url: http://127.0.0.1:8080/return